// <auto-generated />
using System;
using CrudProduto.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudProduto.Migrations
{
    [DbContext(typeof(CrudProdutoContext))]
    [Migration("20200629185241_M")]
    partial class M
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CrudProduto.Models.Acessorio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("LinhaProdutoid");

                    b.Property<int?>("Produtoid");

                    b.Property<string>("descLog");

                    b.Property<string>("descricao");

                    b.Property<string>("nome");

                    b.Property<int>("quantidade");

                    b.HasKey("id");

                    b.HasIndex("LinhaProdutoid");

                    b.HasIndex("Produtoid");

                    b.ToTable("Acessorio");
                });

            modelBuilder.Entity("CrudProduto.Models.FichaTecnica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("categoria");

                    b.Property<string>("componenteBasico");

                    b.Property<string>("componentePrimario");

                    b.Property<string>("componenteSecundario");

                    b.Property<string>("descLog");

                    b.Property<string>("descricao");

                    b.Property<string>("subCategoria");

                    b.HasKey("id");

                    b.ToTable("FichaTecnica");
                });

            modelBuilder.Entity("CrudProduto.Models.LinhaProduto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descLog");

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.ToTable("LinhaProduto");
                });

            modelBuilder.Entity("CrudProduto.Models.Log", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dataHora");

                    b.Property<string>("descLog");

                    b.Property<string>("descricao");

                    b.Property<int>("idUsuario");

                    b.HasKey("id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("CrudProduto.Models.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("comprador");

                    b.Property<DateTime>("dataCompra");

                    b.Property<string>("descLog");

                    b.Property<int?>("fichaTecnicaid");

                    b.Property<int?>("linhaProdutoid");

                    b.Property<string>("nome");

                    b.Property<int>("quantidade");

                    b.Property<bool>("status");

                    b.Property<double>("valorCompra");

                    b.HasKey("id");

                    b.HasIndex("fichaTecnicaid");

                    b.HasIndex("linhaProdutoid");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("CrudProduto.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descLog");

                    b.Property<string>("nome");

                    b.Property<string>("senha1");

                    b.Property<string>("senha2");

                    b.HasKey("id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CrudProduto.Models.Acessorio", b =>
                {
                    b.HasOne("CrudProduto.Models.LinhaProduto")
                        .WithMany("acessorios")
                        .HasForeignKey("LinhaProdutoid");

                    b.HasOne("CrudProduto.Models.Produto")
                        .WithMany("acessorios")
                        .HasForeignKey("Produtoid");
                });

            modelBuilder.Entity("CrudProduto.Models.Produto", b =>
                {
                    b.HasOne("CrudProduto.Models.FichaTecnica", "fichaTecnica")
                        .WithMany()
                        .HasForeignKey("fichaTecnicaid");

                    b.HasOne("CrudProduto.Models.LinhaProduto", "linhaProduto")
                        .WithMany()
                        .HasForeignKey("linhaProdutoid");
                });
#pragma warning restore 612, 618
        }
    }
}
